gcivil-nyu-org/team-4-inperson

ratenyu/courses/admin.py
ratenyu/courses/apps.py
ratenyu/courses/models.py
ratenyu/courses/tests.py
ratenyu/courses/views.py
ratenyu/professors/admin.py
ratenyu/professors/apps.py
ratenyu/professors/models.py
ratenyu/professors/tests.py
ratenyu/professors/views.py
ratenyu/ratenyu/urls.py
ratenyu/search/admin.py
ratenyu/search/apps.py
ratenyu/search/models.py
ratenyu/search/tests.py
ratenyu/search/urls.py
ratenyu/search/views.py

- Search
- Courses
- Professors

Created apps for project

---

ratenyu/ratenyu/settings.py
ratenyu/search/templates/search/courseResult.html
ratenyu/search/templates/search/index.html
ratenyu/search/templates/search/professorResult.html
ratenyu/search/urls.py
ratenyu/search/views.py

Add dummy template for search, course result, and professor result. Added views using those templates and configured the urls.

update views and urls config

---

ratenyu/.ebextensions/02_django.config
ratenyu/ratenyu/settings/prod.py
ratenyu/ratenyu/wsgi.py

After we merge this to Dev, I will re-deploy dev server to confirm everything is good. There should be no issues.

Added Prod server configurations

---

ratenyu/courses/templates/courses/detail.html
ratenyu/courses/views.py
ratenyu/professors/templates/professors/detail.html
ratenyu/professors/views.py

Pulling latest code into courseid before merging it with develop

Link professor course (#108)

---

ratenyu/courses/course_util.py
ratenyu/courses/templates/courses/detail.html
ratenyu/courses/tests.py
ratenyu/courses/views.py
ratenyu/professors/templates/professors/detail.html

- Travis pipeline is successful (this will cover the test cases passing)
- Course Detail Page still renders successfully with the correct format based on UI mockup
- Links from Course Detail Page to Professor Detail Page still work

Modularized course detail view and added tests

---

ratenyu/courses/course_util.py
ratenyu/courses/templates/courses/detail.html
ratenyu/courses/tests.py
ratenyu/professors/templates/professors/detail.html
ratenyu/professors/tests.py
ratenyu/professors/views.py

- Professor Detail Page still renders successfully
- Links on professor detail (to course detail) and course detail page (to professor detail) still functional
- Unit tests passing (confirmed by Travis build)

Modularized Professor Detail view and added Tests

---

ratenyu/search/search_util.py
ratenyu/search/views.py

Updated query filter to work with Postgres. Stripped whitespace from query value.

Course Results Filtering Hotfix

---

ratenyu/ratenyu/urls.py
ratenyu/static/css/style.css
ratenyu/templates/error.html
ratenyu/util/urls.py
ratenyu/util/views.py

"Added a new error page."
Definition of done:
Error page should display the error that has been passed while rendering the html file. 
How to test: 
Call the error404 function from anywhere in your code. It should display.

Error Page

---

ratenyu/search/search_util.py
ratenyu/search/templates/search/professorResult.html
ratenyu/search/tests.py
ratenyu/search/views.py

User can search by professor name 
User will see results for a for professor name (if results exist) or see 'no result for <query>' (if no results exist)
User can click link for matching results to see the respective professor detail pages

professor results & tests

---

ratenyu/search/tests.py
ratenyu/search/views.py

While rebasing the logging branch, i had overwritten some of the changes committed by Elizabeth.
I have added those and also modified the test case so that in future same mistake gets caught.

Fixed bug created in merging and modified tests

---

.ebextensions/django_dev.config
.ebextensions/django_prod.config
.gitignore
.travis.yml
ratenyu/ratenyu/settings/dev.py
ratenyu/ratenyu/settings/prod.py

I have made the changes to make the deployment work in EBS

Changes done to avoid deployment failing in EBS

---

ratenyu/courses/views.py
ratenyu/manage.py
ratenyu/professors/views.py
ratenyu/search/templates/search/courseId.html
ratenyu/search/tests.py
ratenyu/search/views.py
ratenyu/static/css/style.css
ratenyu/templates/error.html

1.  The error page must display error message
2.  The error page must display the error
3.  When  a user gives wrong course id, a no results page must be displayed.
4.  FIxed the user panel bugs

Make error page look better

---

ratenyu/courses/tests.py

Added tests for add review functionality

Test for more coverage on add_review functionality

---

ratenyu/users/tests.py
ratenyu/users/views.py

DOD:
1. Passing all the scenarios of Test cases for user profile
2. In case user is logged out and tries to view the profile, redirect it to the search page.

Added tests for profile page and fixed logged out bug

---

ratenyu/courses/tests.py
ratenyu/courses/views.py
ratenyu/professors/views.py
ratenyu/search/templates/search/courseId.html
ratenyu/search/tests.py
ratenyu/search/views.py
ratenyu/static/css/style.css
ratenyu/templates/error.html
ratenyu/users/tests.py
ratenyu/users/views.py

* Make error page look better
* Make changes to user panel and no courseId
* update tests
* remove base
* change raise to return

PR to pull latest changes to Prod

---

ratenyu/courses/views.py
ratenyu/ratenyu/settings/base.py
ratenyu/ratenyu/settings/dev.py
ratenyu/ratenyu/settings/prod.py
ratenyu/search/views.py

I have changed the logging format in the file. 
Now the logs will be printed as per the following format.
"[(asctime)] [(levelname)] [(relativepath):(lineno)] (message)"
How to use logging in your files? 
Refer this updated document. 
https://docs.google.com/document/d/1G1Qsu4p0wC1RXvnHmYaMFUvujdaQcMvFwJLvzl2J3Is/edit
I have also changed the logging for files to have stack trace printed.

Changed logging format

---

ratenyu/courses/templates/courses/detail.html
ratenyu/professors/templates/professors/detail.html
ratenyu/static/css/style.css
ratenyu/static/javascript/script.js

1. Users can filter reviews by courses on Professor detail page.
2. Users can filter reviews by professor on Course detail page.

Details filtering

---

ratenyu/courses/models.py
ratenyu/courses/templates/courses/add_review.html
ratenyu/courses/templates/courses/detail.html
ratenyu/professors/templates/professors/detail.html

Definition of done. 
When someone writes a review, the maximum characters allowed to be typed should be 2200.
This has to be from all the three methods: 
1. from "Add review" page
2. from course details page
3. from professor details page.

Set Review Text Character Limit tp 2200

---

ratenyu/courses/templates/courses/add_review.html
ratenyu/courses/templates/courses/detail.html
ratenyu/courses/views.py
ratenyu/professors/templates/professors/detail.html
ratenyu/static/css/style.css
ratenyu/static/javascript/script.js
ratenyu/users/templates/users/login.html
ratenyu/users/templates/users/register.html

1. Refreshing page does not submit multiple reviews or mess with registration page
2. Multiple clicks have been disabled on add review button and create account button

Resubmit fix

---

ratenyu/courses/templates/courses/detail.html
ratenyu/professors/templates/professors/detail.html
ratenyu/static/javascript/script.js
ratenyu/users/templates/users/profile.html

Kindly ignore the branch name.
Added no reviews message on pages where reviews are displayed.
Definition of done:
1. Course Details Page: On a course details page, if there are no reviews for the course, it should display appropriate message. If there are reviews for only one professor and reviews are filtered for other professor it should display no reviews message. 
2. Professor Details Page: On professor details page, if there are no reviews for the professor, it should display appropriate message. If there are reviews for only one course and reviews are filtered for other courses it should display no reviews message. 
3. Profile page: If there are no reviews written by a user, it should display appropriate message on profile page
In all the scenarios if there is at least one review …

Issue fix 204

---

ratenyu/courses/tests.py
ratenyu/courses/urls.py
ratenyu/courses/views.py
ratenyu/static/css/style.css
ratenyu/static/javascript/script.js
ratenyu/users/templates/users/profile.html

Description of done: 
logged in user can edit their reviews from user profiles page:
-can edit review rating and review text
-save saves the changes; cancel does not save the changes
-user cannot change their review to contain profanity

Edit review

---

ratenyu/courses/templates/courses/detail.html
ratenyu/professors/templates/professors/detail.html
ratenyu/static/javascript/script.js

Definition of Done: 
-on course and professor detail pages, reviews are default sorted by review date descending order 
-user can sort by review date descending, review date ascending, rating descending, rating ascending using the dropdown selector

Sort details pages

---

ratenyu/users/templates/users/login.html

An error message is displayed if wrong credentials are entered.

Add error message after login failure

---

ratenyu/ratenyu/settings/dev.py
ratenyu/util/urls.py
ratenyu/util/views.py

Reverts gcivil-nyu-org/team-4-inperson#238

Revert "Redirecting incorrect Urls"

---

ratenyu/search/tests.py
ratenyu/search/views.py

- On valid Search by Course ID, user is redirected to Course Detail page AND URL is updated to Course Detail URL ("/courses/{course_id}"), instead of Search Query URL.

Redirect courseid search

---

ratenyu/courses/course_util.py
ratenyu/courses/templates/courses/detail.html
ratenyu/courses/tests.py
ratenyu/courses/views.py
ratenyu/professors/templates/professors/detail.html
ratenyu/professors/tests.py
ratenyu/professors/views.py
ratenyu/search/templates/search/courseResult.html
ratenyu/search/templates/search/professorResult.html
ratenyu/search/tests.py
ratenyu/search/views.py
ratenyu/static/css/style.css
ratenyu/users/forms.py
ratenyu/users/templates/users/profile.html
ratenyu/users/templates/users/register.html
ratenyu/users/tests.py
ratenyu/users/views.py

Definition of done:
1. In details pages and profile page, there will be 10 reviews on each page. In result pages, there will be 10 results on each page.
2. user is able to view the next page by click next button if exist.
3. user is able to view the previous page by click previous button if exist.
4. user is able to view the last page by click last button.
5. user is able to view the first page by click first button.
6. user is able to type the page number in the url and direct to the specific page. If the number is not integer, they will direct to the first page. If the number is out of range, they will direct to the last page.
------------------------------------------------------------------------------------------
BUGS:
1. fix the bug so that navbar1 will appear in the registration …

Pagination

---

ratenyu/courses/course_util.py
ratenyu/professors/tests.py
ratenyu/users/tests.py

Added the unit test for pagination and edit profile, the coverage went up.

Edit profile test and pagination test

---

ratenyu/courses/course_util.py
ratenyu/search/search_util.py
ratenyu/search/tests.py

DOD:
On the search page when you search without spaces, the search takes you to the course details page.
1. CSGY 6063
2. CSGY6063 
These redirect you to Software Engineering pages

Enabled Courseid search with CSGY

---

ratenyu/static/css/style.css
ratenyu/users/templates/users/profile.html

On the edit profile, the user should not able to enter more than 100 characters for Name and Major. 
Note: The change still allows blank spaces as that is not part of this bug fix.

Set maxlength in edit profile form

---

ratenyu/static/css/style.css

Definition of Done.
On the homepage, when the window size is reduced, the text should not get squished. The text should move on the next line.

Text gets on next line.

---

ratenyu/courses/templates/courses/detail.html
ratenyu/courses/views.py
ratenyu/professors/templates/professors/detail.html
ratenyu/professors/views.py
ratenyu/search/templates/search/courseResult.html
ratenyu/static/css/style.css
ratenyu/static/javascript/script.js
ratenyu/templates/base.html
ratenyu/users/templates/users/profile.html
ratenyu/users/urls.py
ratenyu/users/views.py

- Review containers on Course Detail, Profile Detail, and Profile Page (+ Edit/Delete buttons) all match the attached image
- If # Likes is > 0, number is colored green. Else, it is black
- If # Dislikes is > 0, number is colored red. Else, it is black.
- If Rating > 2.5, it is colored green. Else, it is red.
- Thumbs Up/Thumbs Down button remains at a larger font when a User has clicked it.
- SITE WIDE - line spacing increased to 1.5rem

Review Container UI Redesign

---

ratenyu/static/css/style.css
ratenyu/templates/socialaccount/login.html

- Google icon does not overlap with text when window size shrinks
- Text is hidden but does not go outside the border of the button when window size shrinks

Google icon overlapping fix

---

ratenyu/search/templates/search/courseResult.html
ratenyu/static/css/style.css
ratenyu/static/javascript/script.js

1. Put the reviews inside containers
2. Make the containers large on hover
3. Make the containers clickable

Course result

---

ratenyu/courses/templates/courses/detail.html
ratenyu/professors/templates/professors/detail.html

1. Filter professor/course detail page based on the left panel

Fix filters on details page

---

.gitignore
ratenyu/static/css/style.css
ratenyu/users/forms.py
ratenyu/users/models.py
ratenyu/users/templates/users/my_courses.html
ratenyu/users/templates/users/profile.html
ratenyu/users/tests.py
ratenyu/users/views.py

*Ignore the branch name*
Definition of done:
Instead of having an open ended major on registration and edit profile, users will be given an option to select from the dropdown. There is also and "others(not listed)" in case a user is registered in some other major than the ones available in the drop down.

Major field changed to  dropdown

---

ratenyu/search/search_util.py
ratenyu/search/templates/search/courseResult.html
ratenyu/search/views.py
ratenyu/static/css/style.css
ratenyu/static/javascript/script.js

- Checking/Unchecking any of filters on Course Results page reloads the page with filters applied
- Filtering applies to ALL results, not just current page
- On "No results found for..." page, the Filtering checkboxes are still available
- URL does not change with filtering

Moved Course Results Page filtering to back end

---

ratenyu/courses/templates/courses/detail.html
ratenyu/static/css/style.css
ratenyu/static/javascript/script.js

Definition of done. 
1. When the save course form is visible, the review block should go on the next line. 
2. When you click on "Add Review" and "Save Course" is visible, then it should hide.. and vice versa. 
3. Cancel button on "Save Course" form should hide the form and not save anything in the database. 
4. Rest all functionality of the page should remain as is.

Course details page improvements

---

ratenyu/courses/course_util.py
ratenyu/courses/templates/courses/detail.html
ratenyu/courses/views.py
ratenyu/professors/templates/professors/detail.html
ratenyu/professors/views.py

On Course Details and Professor Details:
-if there is only one page of reviews sorting should function as normal 
-if there are multiple pages of reviews, sorting should persist across page changes

Detail sorting
